Repository openshift/kubernetes-sigs-kueue, pull requests merged in 2025-08, with the labels that each got.

#233 Add s390x support to release-0.12 pipeline
  .tekton/kueue-0-12-pull-request.yaml
  .tekton/kueue-0-12-push.yaml
Labels: kind/feature, lgtm, approved, ok-to-test

#255 MULTIARCH-5625: Adding support for ppc64le for kueue
  .tekton/kubernetes-sigs-kueue-main-pull-request.yaml
  .tekton/kubernetes-sigs-kueue-main-push.yaml
Labels: kind/feature, lgtm, approved, jira/valid-reference

#274 MULTIARCH-5625: Adding support for ppc64le for kueue on release-0.12
  .tekton/kueue-0-12-pull-request.yaml
  .tekton/kueue-0-12-push.yaml
Labels: kind/feature, lgtm, approved, jira/valid-reference

#276 Add arm64 arch support for release-0.12
  .tekton/kueue-0-12-pull-request.yaml
  .tekton/kueue-0-12-push.yaml
Labels: kind/feature, lgtm, approved
